---
- name: Ensure unattended-upgrades package is installed
  ansible.builtin.apt:
    name:
      - unattended-upgrades
    state: present
  become: true

- name: Copy 20auto-upgrades
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Copy 50unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'

- name: Ensure unattended-upgrades service is restarted and enabled
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    state: restarted
    enabled: true
